### ISSUE TITLE
View Animal

### ISSUE THREAD

**Issue by cookiewho** [cookiewho/CST438-Project-1-Group-4#5]
As the user, when I am logged in, I should be able to see a list of animal pictures
- [x] grab picture URLs 
- [x] use [Glide](https://github.com/bumptech/glide) in order to fetch the picture from the URL we grabbed in the task before to be able to view the picture without downloading them.
- [x] attach each image to an image view inside of recycler view items.

**Comment by GuillermoFloresV** [comment]
pull picture from api and display the image inside of a recycler view.

**Comment by GuillermoFloresV** [comment]
Done for Dog API with this [commit](https://github.com/cookiewho/CST438-Project-1-Group-4/commit/50c4d63dc48d385505fd13e07e803c3b0ebb0d85)

**Comment by GuillermoFloresV** [comment]
Ultimately finished with this [commit](https://github.com/cookiewho/CST438-Project-1-Group-4/commit/7fec4cb2a7fcb6bed3b2d17ed720286a73e10b34) which added functionality for the cat picture API
